<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Terraria Boss
email: 418648118@qq.com
description: 日常指南·群服公告
  
baseurl: "" # the subpath of your site, e.g. /blog
url: http://ExXiaoR.coding.me

#sidebar
default-image: default-image.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: 小r
copyright:
   name: Terraria Boss
   link: 'http://tr.xcoder.cc/'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
# analytics:

# Comments
# disqus-shortname: 

#social
github: https://github.com/mst-mrh
steam: http://steamcommunity.com/groups/trboss
# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

=======
theme: jekyll-theme-architect
>>>>>>> 4bbbb56c68b54e4c948550e19b0df68feec71998
